### ISSUE TITLE
rux-input does not support handling onpaste

### ISSUE THREAD

**Issue by raven2500** [RocketCommunicationsInc/astro#959] opened 2022-11-29 22:34 UTC
**Describe the bug**
The input element handles the onpaste event, but rux-input does not.

**To Reproduce**

1. added a rux-input field with (ruxinput)=onInput().  onInput is called when text is entered, but pasting text into the field does not trigger the onInput

**Current behavior**
(ruxinput) is not triggered when a paste is done

**Expected behavior**
onpaste would be available to handle a paste into the input field 

**Screenshots**

**CodeSandbox**
If applicable, please provide a CodeSandbox or other online code editor tool link that contains an example of the bug.

**Environment (please complete the following information):**

- @astrouxds/astro-web-components version [e.g. 7.0.0]
- Framework, if applicable (React, Angular, Vue, Svelte, ect)
- Framework wrapper version, if applicable (@astrouxds/react or @astrouxds/angular)

**Additional context**

**Comment by FMorrison87** [comment] 2022-11-30 16:25
@raven2500 I reproduced this as best I could in an Angular sandbox: https://codesandbox.io/s/unruffled-blackwell-n47l7g?file=/src/app/app.component.html

From what I can see with the way I have it setup, the console log fires both when input is entered manually, and via paste. If possible, could you send along more context or a sandbox of your own for how this bug looks in your environment?

**Comment by FMorrison87** [comment] 2023-01-19 17:14
Closing this issue due to no more information from the original reporter.

**Closed by FMorrison87** 2023-01-19 17:14 UTC
Labels: question, angular
